# Generated by Django 2.0.6 on 2018-07-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNum', models.CharField(max_length=25)),
                ('partDesc', models.CharField(max_length=50)),
                ('lineLoc', models.CharField(max_length=25)),
                ('lineQuantity', models.CharField(max_length=5)),
                ('lineMakeup', models.CharField(max_length=5)),
                ('sysQuantity', models.CharField(max_length=5)),
                ('comments', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
